server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://192.168.186.128:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  #thymeleaf
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging.level:
  com.biubiu.myblog.dao: debug

#nacos.config.server-addr: 127.0.0.1:8848


knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.biubiu.myblog